/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GzpVXdR3KGc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex justify-center items-center py-5 mt-5" >
      <Card className="w-[80%]  rounded-xl " style={{ background: "#3e66fb" }}>
        <CardHeader>
          <CardTitle><span className="text-white">Get The App</span></CardTitle>
          <CardDescription>
            <p className="mt-5 text-white">Fill out the form below and we&apos;ll get back to you as soon as possible.</p>
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="name"><span className="text-white">Name</span></Label>
              <Input id="name" placeholder="Enter your name" className="text-white" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email"> <span className="text-white">Email</span> </Label>
              <Input id="email" placeholder="Enter your email" className="text-white"type="email" />
            </div>
          </form>
        </CardContent>
        <CardFooter>
          <Button className="text-white" style={{ background: '#3e66f' }}>Send</Button>
        </CardFooter>
      </Card>
    </div>
  )
}
